name: React CI
'on':
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CI
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install
      - run: npm run build --if-present
      - run: npm run test
      - name: CD
      - uses: appleboy/scp-action@master
        with:
          key: '${{ secrets.PRIVATE_KEY }}'
          host: '${{ secrets.${{ secrets.USERNAME }} }}'
          username: '${{ secrets.USERNAME }}'
          passphrase: ''
          source: build/
          target: /home/benjamin/web
