name: React CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: CI
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install 
      - run: npm run build --if-present
      - run: npm run test
    - name: CD
      uses: garygrossgarten/github-action-scp@release
      with:
        local: build
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
      