name: React CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: CI
      uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - run: npm install 
    - run: npm run build --if-present
    - run: npm run test
    - name: CD
      uses: appleboy/scp-action@master
      with:
        key: ${{ secrets.PRIVATE_KEY }}
        host: ${{ secrets.HOST  }}
        username: ${{ secrets.USERNAME }}
        passphrase: ""
        source: "Dockerfile,build/"
        target: "/home/${{ secrets.USERNAME }}/web"

        